name: Code-Testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Install Golang"
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: "Install all dependencies"
        run: |
                go mod download
        
      - name: "Run Tests"
        run: |
          go test
